### ISSUE TITLE
Unable to build spago

### ISSUE THREAD

**Issue by masaeedu** [nmattia/snack#124]
Hi there. I was trying out building https://github.com/spacchetti/spago using the following `snack.nix` file:

```
let
  nixpkgs = import <nixpkgs> {};
in
with nixpkgs.haskell.lib;
let
  # Necessary to patch packages that are broken in default nixpkgs
  # See: https://qiita.com/kimagure/items/c3fb87f7f71b9df99078
  hsOverrides = hp: with hp; hp // {
    async-pool = overrideCabal async-pool (old: {
      jailbreak = true;
      doCheck = false;
      broken = false;
    });
  };
  # ghc 8.6.5
  gwp  = nixpkgs.ghc.withPackages;
  gwp' = f: gwp (hp: f (hsOverrides hp));
in
rec {
  ghcWithPackages = gwp';
  pkgs = nixpkgs;
}
```

However I get the following error:

```
... lots of output ...
Building module Spago.TH
Local imports are:
Creating dependencies symtree for module Spago.TH
Creating module symlink for module Spago.TH
Compiling module Spago.TH
ghc: unrecognised flag: -main-is Spago

Usage: For basic information, try the `--help' option.
ghc: unrecognised flag: -main-is Curator
builder for '/nix/store/7qbpcbzi5ahkyxivip6ljc17dap48aac-Spago.Prelude.drv' failed with exit code 1
cannot build derivation '/nix/store/g6y30clfdlxspxf68jhmxkfg0rq3a67a-spago.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/gd7jmz6mkysa5qp13jm83vjlb71cp4d9-build.json.drv': 1 dependencies couldn't be built
error: build of '/nix/store/gd7jmz6mkysa5qp13jm83vjlb71cp4d9-build.json.drv' failed
```

Full output is here: https://gist.github.com/masaeedu/759b0d19591b555ebbe8e5cbf2364cfd

**Comment by nmattia** [comment]
Interesting, can you share your `package.yaml`/`package.nix`? Any idea where the `-main-is` is coming from? Looks like ghc is receiving it as `-main-is Curator` (one arg) as opposed to `-main-is` `Curator` (two args).

**Comment by masaeedu** [comment]
You can take a look here:
https://github.com/spacchetti/spago/blob/master/package.yaml. The ghc
options bit for both executables specifies that flag.

**Comment by masaeedu** [comment]
I changed:

```yaml
executables:
  spago:
    main:                Spago.hs
    source-dirs:         app
    ghc-options:
    - -main-is Spago
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  spago-curator:
    main:                Curator.hs
    source-dirs:         app
    ghc-options:
    - -main-is Curator
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
```

to:

```yaml
executables:
  spago:
    main:                Spago.hs
    source-dirs:         app
    ghc-options:
    - -main-is
    - Spago
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  spago-curator:
    main:                Curator.hs
    source-dirs:         app
    ghc-options:
    - -main-is
    - Curator
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
```

and it managed to get past that step. I think this is a bug, if the intent is to remain hpack (and therefore stack) compatible.
