### ISSUE TITLE
error: attribute 'morpheus-graphql' missing, at /nix/store/01ymwd4kb7hkmh5hz6jsdmvrs1z28l7c-snack-lib/default.nix:57:18

### ISSUE THREAD

**Issue by ar1a** [nmattia/snack#168]
Hi! I'm trying to install `morpheus-graphql` in a simple hpack project. A minimal reproduction is quite easy on my machine. Running NixOS unstable.

package.yaml

```
name: ariahaskellgraphql
version: 0.1.0
executable:
  source-dirs: src
  main: Main.hs
  dependencies:
    - morpheus-graphql
```

src/Main.hs

```haskell
module Main where

main :: IO ()
main = putStrLn "hello world"
```

full log: https://gist.github.com/ar1a/c9fd6d1b5b061737ed1b8d12d3452f6a

on a side note, when i ran `snack build` without the dependencies it built successfully but there was no executable for me to run, i had to go digging through /nix/store. Was this intended?
