### ISSUE TITLE
Include build-tools to dependencies

### ISSUE THREAD

**Issue by thebrodmann** [nmattia/snack#187]
Snack doesn't include build-tools specified in `package.yaml` into the build environment.
As an example:

```yaml
library:
  source-dirs: src
  ghc-options:
    - -F
    - -pgmF=record-dot-preprocessor
  dependencies:
    - record-hasfield
  build-tools:
    - record-dot-preprocessor
```

With the above `package.yaml` file Snack will fail to build and throws the following error:

```bash
ghc: could not execute record-dot-preprocessor
```

After adding `record-dot-preprocessor` to the dependencies Snack can build the project. So it would be rational to suppose `build-tools` as dependencies that should be provided by Snack.
