### ISSUE TITLE
Dependencies with version constraints

### ISSUE THREAD

**Issue by pikajude** [nmattia/snack#38]
e.g. ```error: attribute 'base             >= 4.7 && < 5' missing, at /nix/store/5yv66bqprl22pzbpbq1azx7bjylzsw23-snack-lib/default.nix:27:18```

It looks like snack tries to use every string in the `dependencies` list as an attribute name in the `haskellPackages` set. Should strip trailing spaces & version constraints here.

**Comment by nmattia** [comment]
mh odd, it does strip spaces and version constraints. Can you share your config file @pikajude?

**Comment by pikajude** [comment]
``` yaml
version: 0.2.0.1
synopsis: Tree representations of datatypes
description: >-
  @type-tree@ provides TH splices for generating tree representations of
  the types contained in datatypes. This is useful for, for example,
  generating class instances for a deeply nested datatype.
license: MIT
author: Jude Taylor
category: Language
tested-with: GHC == 7.8.4, GHC == 7.10.3, GHC == 8.0.2, GHC == 8.2.2, GHC == 8.4.3
extra-source-files: ChangeLog.md

github: pikajude/type-tree

ghc-options: -Wall

dependencies: []

custom-setup:
  dependencies:
    - base == 4.*
    - Cabal
    - cabal-doctest >= 1 && < 1.1

library:
  source-dirs: src
  exposed-modules:
    - Language.Haskell.TypeTree
    - Language.Haskell.TypeTree.ExampleDatatypes
  dependencies:
    - base             
    - base-compat      
    - containers
    - mtl
    - pretty
    - template-haskell
  default-extensions: NoImplicitPrelude
  other-extensions:
    - FlexibleInstances
    - CPP
    - TypeSynonymInstances
    - TemplateHaskell
    - DeriveDataTypeable
  ghc-options: -fno-warn-missing-signatures -fno-warn-name-shadowing

tests:
  doctest:
    main: doctests.hs
    source-dirs: tests
    dependencies: [base, doctest]
```
